### ISSUE TITLE
[Build] 프로젝트 생성 및 코드기반 프로그래밍 세팅

### ISSUE THREAD

**Issue by JaewoongLee-swift** [TeamGoodGood/RelayNovel-iOS#1]
**Issue : Feature**
Xcode 프로젝트 생성 및 코드기반 프로그래밍 세팅이 필요합니다.

**Description**
1. Xcode 프로젝트 생성을 해야합니다.
2. 코드기반 프로그래밍 세팅설정이 필요합니다.
3. Swift Package Manager를 통해 SnapKit 프레임워크의 설치가 필요합니다.

**Todo**
- [x] Xcode 프로젝트 생성
- [x] 코드기반 프로그래밍 세팅 설정
- [x] Swift Package Manager를 통한 SnapKit 프레임워크 설치

**Reference(Optional)**
SnapKit : [Link](https://github.com/SnapKit/SnapKit)
