### ISSUE TITLE
[Build] .gitignore 설정

### ISSUE THREAD

**Issue by JaewoongLee-swift** [TeamGoodGood/RelayNovel-iOS#2]
**Issue : Feature**
Xcode 개발을 위한 .gitignore 설정이 필요합니다.

**Description**
1. macOS 관련 gitignore 세팅
2. Xcode 관련 gitignore 세팅
3 Swift 관련 gitignore 세팅

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] macOS 관련 gitignore 세팅
- [x] Xcode 관련 gitignore 세팅
- [x] Swift 관련  gitignore 세팅

**Reference(Optional)**
1. gitignore 설정에 도움이 되는 사이트 : [Link](https://www.toptal.com/developers/gitignore/)
2. gitignore 설정 키워드에서 SwiftPackageManager는 제외해야합니다. 프로젝트 파일이 제거되는 이슈가 있습니다.
